apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tomcat
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
      - name: tomcat
        image: tomcat:latest
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "512Mi" # Set your desired memory limit
            cpu: "500m" # Set your desired CPU limit
          requests:
            memory: "256Mi" # Set your desired memory request
            cpu: "250m" # Set your desired CPU request
