name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      STACK_NAME: ecs-service-connect
      ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
      ECR_REPOSITORY: yelb-app-image
      IMAGE_TAG: ${{ github.sha }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # ... (Add your other steps for building and deploying here)

      - name: List CloudFormation stacks
        run: |
          aws cloudformation describe-stacks --query "Stacks[*].[StackName]" --output table

      - name: Delete CloudFormation stack
        run: |
          aws cloudformation delete-stack --stack-name "${STACK_NAME}"
          aws cloudformation wait stack-delete-complete --stack-name "${STACK_NAME}"
#endline
